sudo: false
dist: trusty
language: python
python:
    - "3.5"
addons:
    apt:
        packages:
            - google-chrome-stable-60.0
install:
    - "pip install -r requirements.txt"
    - "npm install"
    - "mkdir ../database"
    - "python manage.py migrate"
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
    - python manage.py test -v 3
